spring:
  application:
    name: provider
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
server:
  port: 20005
  servlet:
    context-path: /provider
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:20000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}   #
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types[0]: text/xml
      mime-types[1]: application/xml
      mime-types[2]: application/json
      min-request-size: 2048
    response:
      enabled: true