spring:
  application:
    name: consumer
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  cloud:
    loadbalancer:
      retry:
        enabled: true
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #断路器超时时间，默认1000ms
server:
  port: 20002
  servlet:
    context-path: /consumer
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:20000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}   #
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types[0]: text/xml
      mime-types[1]: application/xml
      mime-types[2]: application/json
      min-request-size: 2048
    response:
      enabled: true
provider:
  ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule
      ConnectTimeout: 3000
      ReadTimeout: 3000
      OkToRetryOnAllOperations: true #这个参数指的是是否允许所有的HTTP请求(GET,POST,PUT等)重试。默认值是false，只允许GET请求重试。对于POST等请求，请慎重使用。
      MaxAutoRetriesNextServer: 10
      MaxAutoRetries: 1
      retryableStatusCodes: 500,404,502

